export const testimonials = [
  {
    name: "Michael S.",
    location: "Toronto, ON",
    date: "Jul 14, 2026",
    rating: 5,
    text: "The streaming quality is exceptional, and customer support is always there when needed. Over 25,000 channels, zero buffering, and incredible VOD selection. Best IPTV service I've found in Canada.",
  },
  {
    name: "Sarah J.",
    location: "Vancouver, BC",
    date: "Aug 02, 2026",
    rating: 5,
    text: "Switched from cable and never looked back. The sports coverage is specifically what I was looking for. No lag during the playoffs which is a first for me with any IPTV provider.",
  },
  {
    name: "David R.",
    location: "Montreal, QC",
    date: "Sep 12, 2026",
    rating: 5,
    text: "Setup was incredibly easy on my Firestick. The support team walked me through the installation in less than 5 minutes. High definition quality is actually 4K as advertised.",
  },
  {
    name: "Liam W.",
    location: "Calgary, AB",
    date: "Oct 05, 2026",
    rating: 5,
    text: "Finally an IPTV service that delivers on its promises. The 4K channels are crisp and the catch-up feature is a lifesaver for missed games.",
  },
  {
    name: "Chloe M.",
    location: "Ottawa, ON",
    date: "Nov 18, 2026",
    rating: 5,
    text: "Amazing customer service! They helped me set up my Mag box in minutes. Highly recommend to anyone looking for reliable IPTV in Canada.",
  },
  {
    name: "James T.",
    location: "Edmonton, AB",
    date: "Dec 03, 2026",
    rating: 5,
    text: "The VOD library is massive. It feels like having Netflix, Hulu, and cable all in one. My family loves it, and the price is unbeatable for what you get.",
  },
  {
    name: "Sophie L.",
    location: "Quebec City, QC",
    date: "Jan 15, 2026",
    rating: 5,
    text: "Je suis très satisfaite du service. Le choix de chaînes francophones est excellent et la qualité d'image est toujours au rendez-vous. Merci beaucoup!",
  },
  {
    name: "Robert K.",
    location: "Winnipeg, MB",
    date: "Feb 22, 2026",
    rating: 5,
    text: "I was skeptical at first, but this service blew me away. The EPG (TV Guide) works flawlessly, which was a huge issue with my previous providers.",
  },
  {
    name: "Emma B.",
    location: "Halifax, NS",
    date: "Mar 10, 2026",
    rating: 5,
    text: "Perfect for watching UK TV shows and international news. The streams never freeze and the picture quality is crystal clear on my 65-inch TV.",
  },
  {
    name: "William P.",
    location: "Victoria, BC",
    date: "Apr 08, 2026",
    rating: 5,
    text: "Outstanding service. The WhatsApp support is real and they actually reply within minutes. You don't find that kind of dedication often anymore.",
  },
  {
    name: "Olivia C.",
    location: "Saskatoon, SK",
    date: "May 25, 2026",
    rating: 5,
    text: "Best decision we made this year was cutting the cord and switching to IPTV Canada. Saving over $100 a month and getting way more content.",
  },
  {
    name: "Daniel M.",
    location: "Hamilton, ON",
    date: "Jun 11, 2026",
    rating: 5,
    text: "The sports packages are comprehensive. I get every NHL, NBA, and NFL game without any blackouts. A must-have for any true sports fan.",
  },
  {
    name: "Isabella V.",
    location: "London, ON",
    date: "Jul 05, 2026",
    rating: 5,
    text: "Very user-friendly. I set it up on my Apple TV using an IPTV app and it's been running perfectly for 6 months now. No complaints whatsoever.",
  },
  {
    name: "Matthew G.",
    location: "St. John's, NL",
    date: "Aug 19, 2026",
    rating: 5,
    text: "The selection of movies is updated daily. I never run out of things to watch. The connection is stable even during peak weekend hours.",
  },
  {
    name: "Ava N.",
    location: "Kitchener, ON",
    date: "Sep 28, 2026",
    rating: 5,
    text: "Great value for money. The 2-device connection is perfect for my living room and bedroom. Quality remains top-notch on both simultaneously.",
  },
  {
    name: "Alexander F.",
    location: "Kelowna, BC",
    date: "Oct 14, 2026",
    rating: 5,
    text: "I've tried 4 different IPTV providers before finding this one. The difference in server stability is night and day. This one actually works.",
  },
  {
    name: "Mia W.",
    location: "Laval, QC",
    date: "Nov 02, 2026",
    rating: 5,
    text: "Très bon rapport qualité-prix. L'installation a été rapide et le support technique m'a accompagné pas à pas. Je recommande fortement.",
  },
  {
    name: "Ethan D.",
    location: "Regina, SK",
    date: "Dec 18, 2026",
    rating: 5,
    text: "The catch-up feature is brilliant. I work odd hours and being able to go back and watch the evening news or my favorite shows is incredibly convenient.",
  },
  {
    name: "Charlotte H.",
    location: "Guelph, ON",
    date: "Jan 07, 2026",
    rating: 5,
    text: "Smooth streaming, great channel list, and affordable pricing. It's exactly what I was looking for. The interface is clean and easy to navigate.",
  },
  {
    name: "Benjamin R.",
    location: "Barrie, ON",
    date: "Feb 14, 2026",
    rating: 5,
    text: "I highly recommend the 12-month plan. It's a steal for the amount of premium content you get. I've already got three of my friends to sign up.",
  },
  {
    name: "Amelia P.",
    location: "Sherbrooke, QC",
    date: "Mar 22, 2026",
    rating: 5,
    text: "Excellent service with zero buffering. The adult pin protection is a great feature since I have kids in the house. Very thoughtful design.",
  },
  {
    name: "Jacob S.",
    location: "Red Deer, AB",
    date: "Apr 30, 2026",
    rating: 5,
    text: "They have literally every PPV event. Boxing, UFC, wrestling... all crystal clear and completely lag-free. The sports fan's dream setup.",
  },
  {
    name: "Evelyn K.",
    location: "Sudbury, ON",
    date: "May 12, 2026",
    rating: 5,
    text: "The installation instructions were very clear and simple to follow. I was up and running on my smart TV in less than 10 minutes.",
  },
  {
    name: "Logan C.",
    location: "Oshawa, ON",
    date: "Jun 26, 2026",
    rating: 5,
    text: "Fantastic service. Whenever I've had a minor issue, their WhatsApp team sorted it out almost instantly. True 24/7 support.",
  },
  {
    name: "Harper T.",
    location: "Kingston, ON",
    date: "Jul 09, 2026",
    rating: 5,
    text: "The 4K movies section is spectacular. Looks amazing on an OLED TV. Highly satisfied with my subscription and will definitely renew.",
  },
  {
    name: "Lucas E.",
    location: "Lethbridge, AB",
    date: "Aug 21, 2026",
    rating: 5,
    text: "A huge selection of international channels. It's great being able to watch news and shows from back home. The connection is rock solid.",
  },
  {
    name: "Abigail B.",
    location: "Moncton, NB",
    date: "Sep 04, 2026",
    rating: 5,
    text: "I love the fact that there's no contract. But honestly, the service is so good I wouldn't think of leaving anyway. Highly recommended.",
  }
];
